package Emitria::Web::Model::DB;

use strict;

use Moose;
extends 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Emitria::Schema',
);

=head1 NAME

Emitria::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Emitria::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Emitria::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Jonathan Stowe

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
